#!/usr/bin/env bash

source $(dirname $0)/common.sh

GRAPHICS_OPTS="\
    --env DISPLAY=$DISPLAY \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
"

NVIDIA_OPTS="\
    --env NVIDIA_VISIBLE_DEVICES=all \
    --env NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility \
    --runtime=nvidia \
"

run_container() {
    docker run \
        --interactive \
        --name ${CONTAINER_NAME} \
        --publish 8888:8888 \
        --rm \
        --tty \
        --user user \
        --volume $PWD:/workdir:rw \
        $GRAPHICS_OPTS \
        $NVIDIA_OPTS \
        $CONTAINER_NAME \
        $@ || exit -1
}

run_container $@
